[package]
name = "simple-render-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28.0"
simple-linear-algebra-rs = { git = "https://github.com/BreadAboba228/simple-linear-algebra-rs" }
