[package]
name = "simple-3d-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
simple-linear-algebra-rs = { git = "https://github.com/BreadAboba228/simple-linear-algebra-rs" }
simple-render-rs = { git = "https://github.com/BreadAboba228/simple-render-rs" }
minifb = "0.28.0"
