[package]
name = "simple-3d"
version.workspace = true
edition.workspace = true

[dependencies]
minifb.workspace = true
simple-linear-algebra = { path = "../simple-linear-algebra" }
simple-render = { path = "../simple-render" }
