[package]
name = "simple-render"
version.workspace = true
edition.workspace = true

[dependencies]
minifb.workspace = true
png.workspace = true
simple-linear-algebra = { path = "../simple-linear-algebra" }
